package ru.github.calculator.states;

public enum AvaibleStates {
    AWAITING_CALCULATING,
    AWAITING_CONTINUE_CALCULATING,
    AWAITING_PERCENT,
    AWAITING_SAVE_CALCULATION_HISTORY,
    AWAITING_HISTORY_DISPLAY,
    AWAITING_START,
    AWAITING_SUM,
    AWAITING_TERM,
    AWAITING_EXIT_DEPOSIT_CALCULATOR,
    AWAITING_POST_CALCULATION_RESULT,
    END
}
